  ; BCD TO BINARY
   LXI H,8350H
   LXI B,8360H
   MVI E,0AH   ; COUNTER FOR UPPER*A+LOWER=BINARY
   MVI A,0AH   ; COUNTER FOR NO OF DATA FROM TABLE TO BE CONVERTED
   STA 9876H
   
   	 	
OVR:MOV A,M
   ANI F0H
   RLC
   RLC
   RLC
   RLC
   MOV D,A      ;SEPERATING UPPER NIBBLE
   MVI A,00H
LI:ADD D        ; UPPER NIBBLE * A
   DCR E
   JNZ LI
   MVI E,0AH
   MOV D,A
   MOV A,M
   ANI 0FH      ;SEPERATING LOWER NIBBLE
   ADD D        ;UPPER NIBBLE * A + LOWER NIBBLE
   STAX B       ;STORE RESULT
   INX H
   INX B
   LDA 9876H    ;DCR THE COUNTER FOR NO OF DATA
   DCR A
   STA 9876H
   JNZ OVR
   HLT
   
   

