;BINARY TO BCD FROM 8345 8445 (IF BDC IS < 100)
     LXI H,8345H
     LXI D,8445H
     MVI C,0AH

LP2: MOV A,M
     MOV B,A
     CPI 00H
     JZ SKIP
     MVI A,00H
L1:  ANA A   ; TO RESET THE FLAGS
     ADI 01H
     DAA
     JC ASY   ; IF CARRY, i.e BCD>100 THEN DON'T SAVE
     DCR B
     JNZ L1
SKIP:STAX D
ASY: INX H
     INX D
     DCR C
     JNZ LP2
     HLT


    
